---
kind: pipeline
name: "Test in 3.6"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Test python 3.6"
    #image: python:3.6
    image: erotemic/research:PY_VER_3.6
    commands:
      - . $HOME/.local/conda/etc/profile.d/conda.sh
      - conda activate py3.6
      - pip install pip -U
      - pip install -r requirements.txt 
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwarray.git@dev/0.4.0#egg=kwarray 
      - pip install -v git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.4.0#egg=kwimage --no-use-pep517

      # - ./run_developer_setup.sh
      # - ./run_tests.py
      
      # using pyargs tests the installed package instead of the source one
      - pip install -v --no-use-pep517 .
      - pytest --pyargs kwplot

    volumes:
      - name: ssh
        path: /root/.ssh

trigger:
  event:
    - pull_request
    - push
    - tag

volumes:
  - name: ssh
    host:
      path: /home/vigilant-robot/.ssh


---
kind: pipeline
name: "Test in 2.7"

platform:
  os: linux
  arch: amd64
  
steps:
  - name: "Test python 2.x"
    #image: python:2.7 
    image: erotemic/research:PY_VER_2.7
    commands:
      - . $HOME/.local/conda/etc/profile.d/conda.sh
      - conda activate py2.7
      - pip install pip -U
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwarray.git@dev/0.4.0#egg=kwarray 
      - pip install -v git+ssh://git@gitlab.kitware.com/vigilant/kwimage.git@dev/0.4.0#egg=kwimage --no-use-pep517
      - pip install -r requirements.txt -U

      # - ./run_developer_setup.sh
      # - ./run_tests.py
      
      # using pyargs tests the installed package instead of the source one
      - pip install -v --no-use-pep517 .
      - pytest --pyargs kwplot

    volumes:
      - name: ssh
        path: /root/.ssh

trigger:
  event:
    - pull_request
    - push
    - tag

volumes:
  - name: ssh
    host:
      path: /home/vigilant-robot/.ssh

