[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=77",
]

[project]
name = "kwplot"
description = "The kwplot module"
license = "Apache-2.0"
license-files = [
  "LICENSE",
]
authors = [ { name = "Jon Crall", email = "jon.crall@kitware.com" } ]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
]
dynamic = [
  "dependencies",
  "optional-dependencies",
  "readme",
  "version",
]
urls.Homepage = "https://gitlab.kitware.com/computer-vision/kwplot"

[tool.setuptools]
include-package-data = true
dynamic.dependencies.file = [
  "requirements/runtime.txt",
]
dynamic.optional-dependencies.all.file = [
  "requirements/optional.txt",
  "requirements/headless.txt",
  "requirements/graphics.txt",
  "requirements/build.txt",
  "requirements/qt.txt",
  "requirements/types.txt",
]
dynamic.optional-dependencies.build.file = [
  "requirements/build.txt",
]
dynamic.optional-dependencies.docs.file = [
  "requirements/docs.txt",
]
dynamic.optional-dependencies.graphics.file = [
  "requirements/graphics.txt",
]
dynamic.optional-dependencies.headless.file = [
  "requirements/headless.txt",
]
dynamic.optional-dependencies.linting.file = [
  "requirements/linting.txt",
]
dynamic.optional-dependencies.optional.file = [
  "requirements/optional.txt",
]
dynamic.optional-dependencies.qt.file = [
  "requirements/qt.txt",
]
dynamic.optional-dependencies.tests.file = [
  "requirements/tests.txt",
]
dynamic.optional-dependencies.types.file = [
  "requirements/types.txt",
]
dynamic.readme.file = [
  "README.rst",
]
dynamic.readme.content-type = "text/x-rst"
dynamic.version.attr = "kwplot.__version__"
package-data."*" = [
  "requirements/*.txt",
]
package-data.kwplot = [
  "py.typed",
]
packages.find.where = [
  ".",
]
packages.find.include = [
  "kwplot*",
]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest]
ini_options.addopts = "-p no:doctest --xdoctest --xdoctest-style=google --ignore-glob=setup.py --ignore-glob=dev --ignore-glob=docs"
ini_options.norecursedirs = ".git ignore build __pycache__ dev _skbuild docs"
ini_options.filterwarnings = [
  "default",
  "ignore:.*No cfgstr given in Cacher constructor or call.*:Warning",
  "ignore:.*Define the __nice__ method for.*:Warning",
  "ignore:.*private pytest class or function.*:Warning",
]

[tool.coverage]
run.branch = true
report.exclude_lines = [
  ".*  # nocover",
  ".*  # pragma: no cover",
  ".*if six.PY2:",
  "^ *pass *$",
  "^ *raise",
  "def __repr__",
  "if __name__ == .__main__.:",
  "if _debug:",
  "if 0:",
  "if trace is not None",
  "pragma: no cover",
  "raise AssertionError",
  "raise NotImplementedError",
  "verbose = .*",
]
report.omit = [
  "*/setup.py",
  "kwplot/__main__.py",
]

[tool.xcookie]
tags = [
  "purepy",
  "gitlab",
  "kitware",
  "cv2",
]
mod_name = "kwplot"
repo_name = "kwplot"
pkg_name = "kwplot"
rel_mod_parent_dpath = "."
os = [
  "linux",
  "osx",
  "win",
]
min_python = "3.10"
max_python = "3.13"
version = "{mod_dpath}/__init__.py::__version__"
url = "https://gitlab.kitware.com/computer-vision/kwplot"
author = "Jon Crall"
author_email = "jon.crall@kitware.com"
description = "The kwplot module"
license = "Apache 2"
dev_status = "planning"
remote_host = "gitlab.kitware.com"
remote_group = "computer-vision"
typed = true
typecheck_install_extras = [
  "types",
  "optional",
  "headless",
  "qt",
]
render_doc_images = 1
use_setup_py = false
use_pyproject_requirements = false
enable_gpg = true
workspace_members = []
workspace_sync_versions = false
